### ISSUE TITLE
/user 页面的问题

### ISSUE THREAD

**Issue by Ckins** [laiy/Exchange#22]
1. 目前app基本能run起来，但登陆成功只是返回success,没有页面跳转，usr页面的较多功能不好测试。
2. 对于/user：id 的get方法， 拿到的参数太少了。 因为要根据是否关注了此id 来调整按钮（关注/取消关注），希望后台判断好之后给另一个参数。
3. 当id是自己的时候可以修改个人资料。是否需要另一个路由路径来处理修改个人信息的请求？ 目前版本不能维持登陆状态，难以调试。

**Comment by laiy** [comment]
1. 页面跳转前端JS实现，获取到success之后，因为有错误处理。
2. 这个方法直接返回了一个完整的User对象，你可以遍历fans数组和当前user._id作匹配来确定，想了一下还是后端实现吧，会多提供一个布尔参数isFan供判断。
3. 当前版本当然不能维持登录，因为所有测试数据都是假的，前后对接的时候去掉mock-data才能做真正的行为测试。修改资料的路径在前后对接完成之后在/user这个路由里加，暂时不考虑，避免过度设计，比如post /user/updateIdCard，这些逻辑写起来很简单的，你可以先把按钮写上。

**Comment by Ckins** [comment]
@laiy 关于状态码
这两天开始写页面的js，发送表单认证之后拿回来一个result
但是404的状态码比较特别，拿到之后我的回调函数就失效了
建议换成别的状态码。
