### ISSUE TITLE
注册于用户页面遇到的问题

### ISSUE THREAD

**Issue by Ckins** [laiy/Exchange#4]
<h1>图片路径问题
<h4>在sass内设置背景和组件图片时，路径应该如何设置？以下写法不起作用
  _background-image: url(./img/avatar.jpg)_
<h1>数据模型问题
<h4>在写注册以及用户信息页面时，_密码_ _性别_有必要加入用户的表中
<h1>仓库中的bootstrap.min.css有误
<h4>此文件缺类，疑似损坏，需更换

**Comment by laiy** [comment]
1. 采用相对路径
2. 了解
3. 如有问题可以直接换掉
